(cl:in-package cargo_ants_msgs-msg)
(cl:export '(SINGLE_LAYER_SENSOR-VAL
          SINGLE_LAYER_SENSOR
          ID-VAL
          ID
          DETECTION_FRAME_ID-VAL
          DETECTION_FRAME_ID
          DYNAMIC-VAL
          DYNAMIC
          NUM_POINTS-VAL
          NUM_POINTS
          INDEX_FIRST-VAL
          INDEX_FIRST
          INDEX_LAST-VAL
          INDEX_LAST
          POINT_FIRST-VAL
          POINT_FIRST
          POINT_LAST-VAL
          POINT_LAST
          OBJ_CENTER-VAL
          OBJ_CENTER
          OBJ_SIZE-VAL
          OBJ_SIZE
          POLYLINES-VAL
          POLYLINES
          REF_ACTUAL-VAL
          REF_ACTUAL
          REF_PREVIOUS-VAL
          REF_PREVIOUS
          REF_CENTROID-VAL
          REF_CENTROID
          REF_TYPE-VAL
          REF_TYPE
))