(cl:in-package cargo_ants_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SENSORID-VAL
          SENSORID
          ID-VAL
          ID
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          MEASSTAT-VAL
          MEASSTAT
          EXISTPROB-VAL
          EXISTPROB
          DYNPROP-VAL
          DYNPROP
          LATDISP-VAL
          LATDISP
          LONGDISP-VAL
          LONGDISP
          RELXDOT-VAL
          RELXDOT
          RELXDDOT-VAL
          RELXDDOT
          LATSPEED-VAL
          LATSPEED
          OBSPROB-VAL
          OBSPROB
          ROLLCOUNT-VAL
          ROLLCOUNT
          RCS-VAL
          RCS
))