(cl:in-package cargo_ants_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SENSORID-VAL
          SENSORID
          ID-VAL
          ID
          DIST-VAL
          DIST
          DIST_RMS-VAL
          DIST_RMS
          ANGLE-VAL
          ANGLE
          ANGLE_RMS-VAL
          ANGLE_RMS
          ANGLE_STAT-VAL
          ANGLE_STAT
          VREL-VAL
          VREL
          VREL_RMS-VAL
          VREL_RMS
          PDH0-VAL
          PDH0
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          TYPE-VAL
          TYPE
          RCS-VAL
          RCS
))