- World:
    lines:
      - [ -20, 10, -5, 10 ]
      - [  -5, 10, -5, 25 ]
      - [  -5, 25, 35, 25 ]
      - [  35, 25, 35, 10 ]
      - [  35, 10, 50, 10 ]
      - [ -20, -5, 50, -5 ]
      
- Object:
    name: cnt00
    parent: world
    mount: [ 15, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]
- Object:
    name: cnt01
    parent: world
    mount: [ 16, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]
- Object:
    name: cnt02
    parent: world
    mount: [ 17, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]
- Object:
    name: cnt03
    parent: world
    mount: [ 18, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]
- Object:
    name: cnt04
    parent: world
    mount: [ 19, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]
- Object:
    name: cnt05
    parent: world
    mount: [ 20, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]
- Object:
    name: cnt06
    parent: world
    mount: [ 19, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]
- Object:
    name: cnt07
    parent: world
    mount: [ 20, 20,  0 ]
    lines:
      - [ -1.0, -0.9,  1.0, -0.9 ]
      - [ -1.0,  0.9,  1.0,  0.9 ]
      - [ -1.0, -0.9, -1.0,  0.9 ]
      - [  1.0, -0.9,  1.0,  0.9 ]

- Object:
    name: agv1
    parent: world
    mount: [  2,  2,  0]
    lines:
      - [ -1.3, -1.1,  1.3, -1.1 ]
      - [ -1.3,  1.1,  1.3,  1.1 ]
      - [ -1.3, -1.1, -1.3,  1.1 ]
      - [  1.3, -1.1,  1.3,  1.1 ]
- GenericDrive:
    name: drive1
    parent: agv1
- KinematicControl:
    name: ctrl1
    drive: drive1
    vtrans_max: 2
    vrot_max: 0.2

- Object:
    name: agv2
    parent: world
    mount: [  6,  2,  0]
    lines:
      - [ -1.3, -1.1,  1.3, -1.1 ]
      - [ -1.3,  1.1,  1.3,  1.1 ]
      - [ -1.3, -1.1, -1.3,  1.1 ]
      - [  1.3, -1.1,  1.3,  1.1 ]
- GenericDrive:
    name: drive2
    parent: agv2
- KinematicControl:
    name: ctrl2
    drive: drive2
    vtrans_max: 2
    vrot_max: 0.2

- Object:
    name: agv3
    parent: world
    mount: [ 10,  2,  0]
    lines:
      - [ -1.3, -1.1,  1.3, -1.1 ]
      - [ -1.3,  1.1,  1.3,  1.1 ]
      - [ -1.3, -1.1, -1.3,  1.1 ]
      - [  1.3, -1.1,  1.3,  1.1 ]
- GenericDrive:
    name: drive3
    parent: agv3
- KinematicControl:
    name: ctrl3
    drive: drive3
    vtrans_max: 2
    vrot_max: 0.2

- Plugin:
    name: npm2-containersim
    search: npm2-containersim
- ContainerTeleport:
    name: ct
    wait: 80.0
    containers:
      - cnt00
      - cnt01
      - cnt02
      - cnt03
      - cnt04
      - cnt05
      - cnt06
      - cnt07
    pickups:
      - [ -1, 13, 0 ]
      - [ -1, 16, 0 ]
      - [  7, 21, 0 ]
      - [ 11, 21, 0 ]
      - [ 15, 21, 0 ]
      - [ 19, 21, 0 ]
      - [ 23, 21, 0 ]
      - [ 29, 16, 0 ]
      - [ 29, 13, 0 ]
    placedowns:
      - [  3,  0, 0 ]
      - [  6,  0, 0 ]
      - [  9,  0, 0 ]
      - [ 12,  0, 0 ]
      - [ 15,  0, 0 ]
      - [ 18,  0, 0 ]
      - [ 21,  0, 0 ]
      - [ 24,  0, 0 ]
      - [ 27,  0, 0 ]
- PickPlaceTaskProcess:
    name: ppp1
    container_manager: ct
    control: ctrl1
- PickPlaceTaskProcess:
    name: ppp2
    container_manager: ct
    control: ctrl2
- PickPlaceTaskProcess:
    name: ppp3
    control: ctrl3
    container_manager: ct

- Simulator:
    timestep: 0.1
    state: pause

- FixedCamera:
    name: world_camera
    bounds: [ -10, -10, 40, 40 ]
- ObjectDrawing:
    name: world_drawing
    object: world
- View:
    name: world_view
    camera: world_camera
    drawings:
      - world_drawing
