// Generated by gencpp from file cargo_ants_msgs/ArtsMeasurement.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_ARTSMEASUREMENT_H
#define CARGO_ANTS_MSGS_MESSAGE_ARTSMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct ArtsMeasurement_
{
  typedef ArtsMeasurement_<ContainerAllocator> Type;

  ArtsMeasurement_()
    : remote_id(0)
    , range(0.0)
    , snr(0.0)  {
    }
  ArtsMeasurement_(const ContainerAllocator& _alloc)
    : remote_id(0)
    , range(0.0)
    , snr(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _remote_id_type;
  _remote_id_type remote_id;

   typedef double _range_type;
  _range_type range;

   typedef double _snr_type;
  _snr_type snr;




  typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct ArtsMeasurement_

typedef ::cargo_ants_msgs::ArtsMeasurement_<std::allocator<void> > ArtsMeasurement;

typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsMeasurement > ArtsMeasurementPtr;
typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsMeasurement const> ArtsMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff748bd5ccbe7fdca1e7e91bcc0165c8";
  }

  static const char* value(const ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff748bd5ccbe7fdcULL;
  static const uint64_t static_value2 = 0xa1e7e91bcc0165c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/ArtsMeasurement";
  }

  static const char* value(const ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#id of the remote node\n\
uint8 remote_id\n\
\n\
#raw measurement\n\
float64 range\n\
\n\
#signal to noise ratio\n\
float64 snr\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remote_id);
      stream.next(m.range);
      stream.next(m.snr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArtsMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "remote_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_id);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "snr: ";
    Printer<double>::stream(s, indent + "  ", v.snr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_ARTSMEASUREMENT_H
