// Generated by gencpp from file cargo_ants_msgs/ArtsArray.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_ARTSARRAY_H
#define CARGO_ANTS_MSGS_MESSAGE_ARTSARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cargo_ants_msgs/ArtsMeasurement.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct ArtsArray_
{
  typedef ArtsArray_<ContainerAllocator> Type;

  ArtsArray_()
    : header()
    , home_id(0)
    , measurements()  {
    }
  ArtsArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , home_id(0)
    , measurements(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _home_id_type;
  _home_id_type home_id;

   typedef std::vector< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >::other >  _measurements_type;
  _measurements_type measurements;




  typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> const> ConstPtr;

}; // struct ArtsArray_

typedef ::cargo_ants_msgs::ArtsArray_<std::allocator<void> > ArtsArray;

typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsArray > ArtsArrayPtr;
typedef boost::shared_ptr< ::cargo_ants_msgs::ArtsArray const> ArtsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bb8ca34159c18e2755b00bb6c11a33b";
  }

  static const char* value(const ::cargo_ants_msgs::ArtsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bb8ca34159c18e2ULL;
  static const uint64_t static_value2 = 0x755b00bb6c11a33bULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/ArtsArray";
  }

  static const char* value(const ::cargo_ants_msgs::ArtsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#time stamp and frame id\n\
Header header\n\
\n\
#id of the node making measurements\n\
uint8 home_id\n\
\n\
#array of the measurements\n\
ArtsMeasurement[] measurements\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cargo_ants_msgs/ArtsMeasurement\n\
#id of the remote node\n\
uint8 remote_id\n\
\n\
#raw measurement\n\
float64 range\n\
\n\
#signal to noise ratio\n\
float64 snr\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::ArtsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.home_id);
      stream.next(m.measurements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArtsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::ArtsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::ArtsArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "home_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.home_id);
    s << indent << "measurements[]" << std::endl;
    for (size_t i = 0; i < v.measurements.size(); ++i)
    {
      s << indent << "  measurements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cargo_ants_msgs::ArtsMeasurement_<ContainerAllocator> >::stream(s, indent + "    ", v.measurements[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_ARTSARRAY_H
