// Generated by gencpp from file cargo_ants_msgs/MoveVehicleState.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_MOVEVEHICLESTATE_H
#define CARGO_ANTS_MSGS_MESSAGE_MOVEVEHICLESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct MoveVehicleState_
{
  typedef MoveVehicleState_<ContainerAllocator> Type;

  MoveVehicleState_()
    : header()
    , sensorId(0)
    , pct_throttle(0.0)
    , brakepressed(0.0)
    , fdrive(0.0)
    , gear(0.0)  {
    }
  MoveVehicleState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensorId(0)
    , pct_throttle(0.0)
    , brakepressed(0.0)
    , fdrive(0.0)
    , gear(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _sensorId_type;
  _sensorId_type sensorId;

   typedef float _pct_throttle_type;
  _pct_throttle_type pct_throttle;

   typedef float _brakepressed_type;
  _brakepressed_type brakepressed;

   typedef float _fdrive_type;
  _fdrive_type fdrive;

   typedef float _gear_type;
  _gear_type gear;




  typedef boost::shared_ptr< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> const> ConstPtr;

}; // struct MoveVehicleState_

typedef ::cargo_ants_msgs::MoveVehicleState_<std::allocator<void> > MoveVehicleState;

typedef boost::shared_ptr< ::cargo_ants_msgs::MoveVehicleState > MoveVehicleStatePtr;
typedef boost::shared_ptr< ::cargo_ants_msgs::MoveVehicleState const> MoveVehicleStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b097c588602ddaf6f4d8a7ce0d3ad6d9";
  }

  static const char* value(const ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb097c588602ddaf6ULL;
  static const uint64_t static_value2 = 0xf4d8a7ce0d3ad6d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/MoveVehicleState";
  }

  static const char* value(const ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 sensorId	#id of sensor\n\
\n\
float32 pct_throttle\n\
float32 brakepressed	#break precentage\n\
float32 fdrive			#drive force generated by drivetrain\n\
float32 gear			#gear\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensorId);
      stream.next(m.pct_throttle);
      stream.next(m.brakepressed);
      stream.next(m.fdrive);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveVehicleState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::MoveVehicleState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensorId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensorId);
    s << indent << "pct_throttle: ";
    Printer<float>::stream(s, indent + "  ", v.pct_throttle);
    s << indent << "brakepressed: ";
    Printer<float>::stream(s, indent + "  ", v.brakepressed);
    s << indent << "fdrive: ";
    Printer<float>::stream(s, indent + "  ", v.fdrive);
    s << indent << "gear: ";
    Printer<float>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_MOVEVEHICLESTATE_H
