// Generated by gencpp from file cargo_ants_msgs/ObjectTrackAtSdfArray.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_OBJECTTRACKATSDFARRAY_H
#define CARGO_ANTS_MSGS_MESSAGE_OBJECTTRACKATSDFARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cargo_ants_msgs/ObjectTrackAtSdf.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct ObjectTrackAtSdfArray_
{
  typedef ObjectTrackAtSdfArray_<ContainerAllocator> Type;

  ObjectTrackAtSdfArray_()
    : header()
    , tracks()  {
    }
  ObjectTrackAtSdfArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tracks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::cargo_ants_msgs::ObjectTrackAtSdf_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cargo_ants_msgs::ObjectTrackAtSdf_<ContainerAllocator> >::other >  _tracks_type;
  _tracks_type tracks;




  typedef boost::shared_ptr< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectTrackAtSdfArray_

typedef ::cargo_ants_msgs::ObjectTrackAtSdfArray_<std::allocator<void> > ObjectTrackAtSdfArray;

typedef boost::shared_ptr< ::cargo_ants_msgs::ObjectTrackAtSdfArray > ObjectTrackAtSdfArrayPtr;
typedef boost::shared_ptr< ::cargo_ants_msgs::ObjectTrackAtSdfArray const> ObjectTrackAtSdfArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a8ebfdff3bc40a1f2d61b0a4d39d6cc";
  }

  static const char* value(const ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a8ebfdff3bc40a1ULL;
  static const uint64_t static_value2 = 0xf2d61b0a4d39d6ccULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/ObjectTrackAtSdfArray";
  }

  static const char* value(const ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# timestamp, frame id\n\
Header header\n\
\n\
#set of targets being tracked\n\
ObjectTrackAtSdf[] tracks\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cargo_ants_msgs/ObjectTrackAtSdf\n\
# Single object track from SDF UDP message (Volvo, AT)\n\
# Result of internal datafusion made by Volvo AutoBox SW, which uses ibeo and radars\n\
\n\
\n\
int32 id 			#track id\n\
int32 class_id		#class id of the track:\n\
int32 UNDETERMINED 		= 0\n\
int32 CAR 				= 1\n\
int32 MOTORCYCLE		= 2\n\
int32 TRUCK 			= 3\n\
int32 PEDESTRIAN 		= 4\n\
int32 POLE				= 5\n\
int32 TREE 				= 6\n\
int32 ANIMAL			= 7\n\
int32 GOD				= 8\n\
int32 BICYLCE			= 9\n\
int32 OTHERS			= 10  #unidentified vehicle, piano, speed limit sign, x-sign, ... \n\
\n\
geometry_msgs/Point position 	#Track position (x,y) [m]\n\
geometry_msgs/Point velocity 	#Track velocity (vx,vy) [m/s]\n\
float64 heading 				#Track heading [rad] \n\
float64[4] covariance			#XY covariance matrix [m2/s2]\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tracks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectTrackAtSdfArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::ObjectTrackAtSdfArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tracks[]" << std::endl;
    for (size_t i = 0; i < v.tracks.size(); ++i)
    {
      s << indent << "  tracks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cargo_ants_msgs::ObjectTrackAtSdf_<ContainerAllocator> >::stream(s, indent + "    ", v.tracks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_OBJECTTRACKATSDFARRAY_H
