// Generated by gencpp from file cargo_ants_msgs/Point.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_POINT_H
#define CARGO_ANTS_MSGS_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : px(0.0)
    , py(0.0)  {
    }
  Point_(const ContainerAllocator& _alloc)
    : px(0.0)
    , py(0.0)  {
  (void)_alloc;
    }



   typedef float _px_type;
  _px_type px;

   typedef float _py_type;
  _py_type py;




  typedef boost::shared_ptr< ::cargo_ants_msgs::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::cargo_ants_msgs::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::cargo_ants_msgs::Point > PointPtr;
typedef boost::shared_ptr< ::cargo_ants_msgs::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8d84da246392fb365eadd4fcd9e63f2";
  }

  static const char* value(const ::cargo_ants_msgs::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8d84da246392fb3ULL;
  static const uint64_t static_value2 = 0x65eadd4fcd9e63f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/Point";
  }

  static const char* value(const ::cargo_ants_msgs::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 px\n\
float32 py\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.px);
      stream.next(m.py);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::Point_<ContainerAllocator>& v)
  {
    s << indent << "px: ";
    Printer<float>::stream(s, indent + "  ", v.px);
    s << indent << "py: ";
    Printer<float>::stream(s, indent + "  ", v.py);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_POINT_H
