// Generated by gencpp from file cargo_ants_msgs/RadarObject209.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_RADAROBJECT209_H
#define CARGO_ANTS_MSGS_MESSAGE_RADAROBJECT209_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct RadarObject209_
{
  typedef RadarObject209_<ContainerAllocator> Type;

  RadarObject209_()
    : header()
    , sensorId(0)
    , obj_id(0)
    , index(0)
    , longdisp(0.0)
    , latdisp(0.0)
    , vrellong(0.0)
    , vrellat(0.0)
    , rollcount(0)
    , rcs(0.0)
    , lifetime(0.0)  {
    }
  RadarObject209_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensorId(0)
    , obj_id(0)
    , index(0)
    , longdisp(0.0)
    , latdisp(0.0)
    , vrellong(0.0)
    , vrellat(0.0)
    , rollcount(0)
    , rcs(0.0)
    , lifetime(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _sensorId_type;
  _sensorId_type sensorId;

   typedef uint16_t _obj_id_type;
  _obj_id_type obj_id;

   typedef uint8_t _index_type;
  _index_type index;

   typedef float _longdisp_type;
  _longdisp_type longdisp;

   typedef float _latdisp_type;
  _latdisp_type latdisp;

   typedef float _vrellong_type;
  _vrellong_type vrellong;

   typedef float _vrellat_type;
  _vrellat_type vrellat;

   typedef uint8_t _rollcount_type;
  _rollcount_type rollcount;

   typedef float _rcs_type;
  _rcs_type rcs;

   typedef float _lifetime_type;
  _lifetime_type lifetime;




  typedef boost::shared_ptr< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> const> ConstPtr;

}; // struct RadarObject209_

typedef ::cargo_ants_msgs::RadarObject209_<std::allocator<void> > RadarObject209;

typedef boost::shared_ptr< ::cargo_ants_msgs::RadarObject209 > RadarObject209Ptr;
typedef boost::shared_ptr< ::cargo_ants_msgs::RadarObject209 const> RadarObject209ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55b65dbd73b07d8169b3a3aef6dd3b37";
  }

  static const char* value(const ::cargo_ants_msgs::RadarObject209_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55b65dbd73b07d81ULL;
  static const uint64_t static_value2 = 0x69b3a3aef6dd3b37ULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/RadarObject209";
  }

  static const char* value(const ::cargo_ants_msgs::RadarObject209_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (counterclockwise, if Z is up)\n\
                         # with zero angle being forward along the x axis\n\
\n\
uint16 sensorId\n\
uint16 obj_id			# unique object id\n\
uint8 index				# index of object in the list\n\
float32 longdisp		# longitudinal displacement	[m]\n\
float32 latdisp			# lateral displacement [m]\n\
float32 vrellong		# relative longitudinal velocity [m/s]\n\
float32 vrellat			# relative lateral velocity	[m/s]\n\
uint8 rollcount			# sequence index\n\
float32 rcs				# radar cross-section [dBm^2]\n\
float32 lifetime		# lifetime of track [s]\n\
                        \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::RadarObject209_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensorId);
      stream.next(m.obj_id);
      stream.next(m.index);
      stream.next(m.longdisp);
      stream.next(m.latdisp);
      stream.next(m.vrellong);
      stream.next(m.vrellat);
      stream.next(m.rollcount);
      stream.next(m.rcs);
      stream.next(m.lifetime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarObject209_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::RadarObject209_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::RadarObject209_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensorId: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sensorId);
    s << indent << "obj_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.obj_id);
    s << indent << "index: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.index);
    s << indent << "longdisp: ";
    Printer<float>::stream(s, indent + "  ", v.longdisp);
    s << indent << "latdisp: ";
    Printer<float>::stream(s, indent + "  ", v.latdisp);
    s << indent << "vrellong: ";
    Printer<float>::stream(s, indent + "  ", v.vrellong);
    s << indent << "vrellat: ";
    Printer<float>::stream(s, indent + "  ", v.vrellat);
    s << indent << "rollcount: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rollcount);
    s << indent << "rcs: ";
    Printer<float>::stream(s, indent + "  ", v.rcs);
    s << indent << "lifetime: ";
    Printer<float>::stream(s, indent + "  ", v.lifetime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_RADAROBJECT209_H
