// Generated by gencpp from file cargo_ants_msgs/RadarCluster309.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_RADARCLUSTER309_H
#define CARGO_ANTS_MSGS_MESSAGE_RADARCLUSTER309_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct RadarCluster309_
{
  typedef RadarCluster309_<ContainerAllocator> Type;

  RadarCluster309_()
    : header()
    , sensorId(0)
    , id(0)
    , dist(0.0)
    , dist_rms(0.0)
    , angle(0.0)
    , angle_rms(0.0)
    , angle_stat(0)
    , vrel(0.0)
    , vrel_rms(0.0)
    , pdh0(0)
    , length(0.0)
    , width(0.0)
    , type(0)
    , rcs(0.0)  {
    }
  RadarCluster309_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensorId(0)
    , id(0)
    , dist(0.0)
    , dist_rms(0.0)
    , angle(0.0)
    , angle_rms(0.0)
    , angle_stat(0)
    , vrel(0.0)
    , vrel_rms(0.0)
    , pdh0(0)
    , length(0.0)
    , width(0.0)
    , type(0)
    , rcs(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _sensorId_type;
  _sensorId_type sensorId;

   typedef uint8_t _id_type;
  _id_type id;

   typedef float _dist_type;
  _dist_type dist;

   typedef float _dist_rms_type;
  _dist_rms_type dist_rms;

   typedef float _angle_type;
  _angle_type angle;

   typedef float _angle_rms_type;
  _angle_rms_type angle_rms;

   typedef uint8_t _angle_stat_type;
  _angle_stat_type angle_stat;

   typedef float _vrel_type;
  _vrel_type vrel;

   typedef float _vrel_rms_type;
  _vrel_rms_type vrel_rms;

   typedef uint8_t _pdh0_type;
  _pdh0_type pdh0;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef uint8_t _type_type;
  _type_type type;

   typedef float _rcs_type;
  _rcs_type rcs;




  typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> const> ConstPtr;

}; // struct RadarCluster309_

typedef ::cargo_ants_msgs::RadarCluster309_<std::allocator<void> > RadarCluster309;

typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster309 > RadarCluster309Ptr;
typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster309 const> RadarCluster309ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9e4132423f7a90954d9f680a083d9d0";
  }

  static const char* value(const ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9e4132423f7a909ULL;
  static const uint64_t static_value2 = 0x54d9f680a083d9d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/RadarCluster309";
  }

  static const char* value(const ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (counterclockwise, if Z is up)\n\
                         # with zero angle being forward along the x axis\n\
\n\
uint16 sensorId                         \n\
uint8 id			# target number\n\
float32 dist		# target range	[m]\n\
float32 dist_rms	# target range standard deviation [m]\n\
float32 angle		# target angle	[deg]\n\
float32 angle_rms	# target angle standard deviation [deg]\n\
uint8 angle_stat	# target angle status: 0-expanded target, 1-point target, 2-digital, 3-invalid\n\
float32 vrel		# target relative velocity [m/s]\n\
float32 vrel_rms	# target relative velocity standard deviation [m/s]\n\
uint8 pdh0			# target false alarm probability [%]\n\
float32 length		# target length	[m]\n\
float32 width		# target width	[m]\n\
uint8 type			# target type: 0-no target, 1-oncoming, 2-stationary, 3-traced (same direction)\n\
float32 rcs			# radar cross-section [dBm^2]\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensorId);
      stream.next(m.id);
      stream.next(m.dist);
      stream.next(m.dist_rms);
      stream.next(m.angle);
      stream.next(m.angle_rms);
      stream.next(m.angle_stat);
      stream.next(m.vrel);
      stream.next(m.vrel_rms);
      stream.next(m.pdh0);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.type);
      stream.next(m.rcs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarCluster309_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::RadarCluster309_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensorId: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sensorId);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
    s << indent << "dist_rms: ";
    Printer<float>::stream(s, indent + "  ", v.dist_rms);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "angle_rms: ";
    Printer<float>::stream(s, indent + "  ", v.angle_rms);
    s << indent << "angle_stat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.angle_stat);
    s << indent << "vrel: ";
    Printer<float>::stream(s, indent + "  ", v.vrel);
    s << indent << "vrel_rms: ";
    Printer<float>::stream(s, indent + "  ", v.vrel_rms);
    s << indent << "pdh0: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pdh0);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "rcs: ";
    Printer<float>::stream(s, indent + "  ", v.rcs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_RADARCLUSTER309_H
