// Generated by gencpp from file cargo_ants_msgs/RadarCluster209.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_RADARCLUSTER209_H
#define CARGO_ANTS_MSGS_MESSAGE_RADARCLUSTER209_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct RadarCluster209_
{
  typedef RadarCluster209_<ContainerAllocator> Type;

  RadarCluster209_()
    : header()
    , sensorId(0)
    , azimut(0.0)
    , index(0)
    , rollcount(0)
    , range(0.0)
    , rcs(0.0)
    , vrel(0.0)  {
    }
  RadarCluster209_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensorId(0)
    , azimut(0.0)
    , index(0)
    , rollcount(0)
    , range(0.0)
    , rcs(0.0)
    , vrel(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _sensorId_type;
  _sensorId_type sensorId;

   typedef float _azimut_type;
  _azimut_type azimut;

   typedef uint8_t _index_type;
  _index_type index;

   typedef uint8_t _rollcount_type;
  _rollcount_type rollcount;

   typedef float _range_type;
  _range_type range;

   typedef float _rcs_type;
  _rcs_type rcs;

   typedef float _vrel_type;
  _vrel_type vrel;




  typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> const> ConstPtr;

}; // struct RadarCluster209_

typedef ::cargo_ants_msgs::RadarCluster209_<std::allocator<void> > RadarCluster209;

typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster209 > RadarCluster209Ptr;
typedef boost::shared_ptr< ::cargo_ants_msgs::RadarCluster209 const> RadarCluster209ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b05b5bcee056cb422fac5d2f0c7fc3a2";
  }

  static const char* value(const ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb05b5bcee056cb42ULL;
  static const uint64_t static_value2 = 0x2fac5d2f0c7fc3a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/RadarCluster209";
  }

  static const char* value(const ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (counterclockwise, if Z is up)\n\
                         # with zero angle being forward along the x axis\n\
uint16 sensorId                         \n\
float32 azimut     # azimut [rad]\n\
uint8 index         # track index\n\
uint8 rollcount     # sequence index\n\
float32 range      # range [m]\n\
float32 rcs        # radar cross-section [dBm^2]\n\
float32 vrel       # relative velocity [m/s]\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensorId);
      stream.next(m.azimut);
      stream.next(m.index);
      stream.next(m.rollcount);
      stream.next(m.range);
      stream.next(m.rcs);
      stream.next(m.vrel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarCluster209_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::RadarCluster209_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensorId: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sensorId);
    s << indent << "azimut: ";
    Printer<float>::stream(s, indent + "  ", v.azimut);
    s << indent << "index: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.index);
    s << indent << "rollcount: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rollcount);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "rcs: ";
    Printer<float>::stream(s, indent + "  ", v.rcs);
    s << indent << "vrel: ";
    Printer<float>::stream(s, indent + "  ", v.vrel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_RADARCLUSTER209_H
