// Generated by gencpp from file cargo_ants_msgs/ReferenceTrajectory.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_REFERENCETRAJECTORY_H
#define CARGO_ANTS_MSGS_MESSAGE_REFERENCETRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cargo_ants_msgs/ReferenceTrajectoryPoint.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct ReferenceTrajectory_
{
  typedef ReferenceTrajectory_<ContainerAllocator> Type;

  ReferenceTrajectory_()
    : dt(0.0)
    , header()
    , child_frame_id()
    , ID(0.0)
    , points()  {
    }
  ReferenceTrajectory_(const ContainerAllocator& _alloc)
    : dt(0.0)
    , header(_alloc)
    , child_frame_id(_alloc)
    , ID(0.0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef float _dt_type;
  _dt_type dt;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _child_frame_id_type;
  _child_frame_id_type child_frame_id;

   typedef float _ID_type;
  _ID_type ID;

   typedef std::vector< ::cargo_ants_msgs::ReferenceTrajectoryPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cargo_ants_msgs::ReferenceTrajectoryPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;


    static const float NEW;
     static const float OLD;
 

  typedef boost::shared_ptr< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct ReferenceTrajectory_

typedef ::cargo_ants_msgs::ReferenceTrajectory_<std::allocator<void> > ReferenceTrajectory;

typedef boost::shared_ptr< ::cargo_ants_msgs::ReferenceTrajectory > ReferenceTrajectoryPtr;
typedef boost::shared_ptr< ::cargo_ants_msgs::ReferenceTrajectory const> ReferenceTrajectoryConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const float
      ReferenceTrajectory_<ContainerAllocator>::NEW =
        
          1.0
        
        ;
   

   
   template<typename ContainerAllocator> const float
      ReferenceTrajectory_<ContainerAllocator>::OLD =
        
          0.0
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8702cc44b741fe0d2e1e25180e01c279";
  }

  static const char* value(const ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8702cc44b741fe0dULL;
  static const uint64_t static_value2 = 0x2e1e25180e01c279ULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/ReferenceTrajectory";
  }

  static const char* value(const ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#time start\n\
float32 dt\n\
\n\
Header header\n\
\n\
string child_frame_id\n\
\n\
float32 NEW=1\n\
float32 OLD=0\n\
float32 ID\n\
\n\
ReferenceTrajectoryPoint[] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cargo_ants_msgs/ReferenceTrajectoryPoint\n\
float32 xx\n\
float32 yy\n\
float32 th\n\
float32 xd\n\
float32 yd\n\
float32 thd\n\
float32 xdd\n\
float32 ydd\n\
float32 thdd\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dt);
      stream.next(m.header);
      stream.next(m.child_frame_id);
      stream.next(m.ID);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReferenceTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::ReferenceTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "dt: ";
    Printer<float>::stream(s, indent + "  ", v.dt);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "child_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.child_frame_id);
    s << indent << "ID: ";
    Printer<float>::stream(s, indent + "  ", v.ID);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cargo_ants_msgs::ReferenceTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_REFERENCETRAJECTORY_H
