// Generated by gencpp from file cargo_ants_msgs/Task.msg
// DO NOT EDIT!


#ifndef CARGO_ANTS_MSGS_MESSAGE_TASK_H
#define CARGO_ANTS_MSGS_MESSAGE_TASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cargo_ants_msgs/Goal.h>
#include <cargo_ants_msgs/Goal.h>

namespace cargo_ants_msgs
{
template <class ContainerAllocator>
struct Task_
{
  typedef Task_<ContainerAllocator> Type;

  Task_()
    : vehicle()
    , container()
    , pickup()
    , placedown()  {
    }
  Task_(const ContainerAllocator& _alloc)
    : vehicle(_alloc)
    , container(_alloc)
    , pickup(_alloc)
    , placedown(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _vehicle_type;
  _vehicle_type vehicle;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _container_type;
  _container_type container;

   typedef  ::cargo_ants_msgs::Goal_<ContainerAllocator>  _pickup_type;
  _pickup_type pickup;

   typedef  ::cargo_ants_msgs::Goal_<ContainerAllocator>  _placedown_type;
  _placedown_type placedown;




  typedef boost::shared_ptr< ::cargo_ants_msgs::Task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cargo_ants_msgs::Task_<ContainerAllocator> const> ConstPtr;

}; // struct Task_

typedef ::cargo_ants_msgs::Task_<std::allocator<void> > Task;

typedef boost::shared_ptr< ::cargo_ants_msgs::Task > TaskPtr;
typedef boost::shared_ptr< ::cargo_ants_msgs::Task const> TaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cargo_ants_msgs::Task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cargo_ants_msgs::Task_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cargo_ants_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'cargo_ants_msgs': ['/home/jendav/catkin_ws/src/code/cargo-ants-ros-pkgs/cargo_ants_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::Task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cargo_ants_msgs::Task_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::Task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cargo_ants_msgs::Task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::Task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cargo_ants_msgs::Task_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cargo_ants_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4de459da6edc0969edecda788239a02b";
  }

  static const char* value(const ::cargo_ants_msgs::Task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4de459da6edc0969ULL;
  static const uint64_t static_value2 = 0xedecda788239a02bULL;
};

template<class ContainerAllocator>
struct DataType< ::cargo_ants_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cargo_ants_msgs/Task";
  }

  static const char* value(const ::cargo_ants_msgs::Task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cargo_ants_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string vehicle\n\
string container\n\
Goal pickup\n\
Goal placedown\n\
\n\
================================================================================\n\
MSG: cargo_ants_msgs/Goal\n\
# A goal is specified as its (gx,gy) coordinate and heading gth (for\n\
# \"goal theta\"). Additionally, dr is the radial tolerance, and dth the\n\
# angular tolerance to be achieved. Specifying a negative number for\n\
# either dr or dth disabled that particular tolerance. Thus, if you do\n\
# no care about the heading with which you arrive at a goal, specify\n\
# dth = -1 for example.  The goal message type is intended to be used\n\
# as part of other messages such as Path.msg, thus we do not include\n\
# the frame here as that should be the same for an entire array of\n\
# goals.\n\
\n\
float64 gx\n\
float64 gy\n\
float64 gth\n\
\n\
# Radial accuracy of the goal. Specifying dr <= 0.0 means that you do\n\
# not care about the goal position at all.\n\
#\n\
float64 dr\n\
\n\
# Angular accuracy of the goal. Specifying dth <= 0.0 or >= M_PI means\n\
# that orientation does not matter.\n\
#\n\
float64 dth\n\
\n\
\n\
#later? bool go_forward\n\
";
  }

  static const char* value(const ::cargo_ants_msgs::Task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cargo_ants_msgs::Task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle);
      stream.next(m.container);
      stream.next(m.pickup);
      stream.next(m.placedown);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cargo_ants_msgs::Task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cargo_ants_msgs::Task_<ContainerAllocator>& v)
  {
    s << indent << "vehicle: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.vehicle);
    s << indent << "container: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.container);
    s << indent << "pickup: ";
    s << std::endl;
    Printer< ::cargo_ants_msgs::Goal_<ContainerAllocator> >::stream(s, indent + "  ", v.pickup);
    s << indent << "placedown: ";
    s << std::endl;
    Printer< ::cargo_ants_msgs::Goal_<ContainerAllocator> >::stream(s, indent + "  ", v.placedown);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARGO_ANTS_MSGS_MESSAGE_TASK_H
