# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cargo_ants_msgs/ObstacleMap.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cargo_ants_msgs.msg

class ObstacleMap(genpy.Message):
  _md5sum = "e166b16de200e7fdba8d6a003a53be73"
  _type = "cargo_ants_msgs/ObstacleMap"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Obstacle[] obstacles

================================================================================
MSG: cargo_ants_msgs/Obstacle
uint32 UNKNOWN=0
uint32 CONTAINER=1
uint32 type_tag

Origin origin
Polyline[] polylines

================================================================================
MSG: cargo_ants_msgs/Origin
float32 ox
float32 oy
float32 oth

================================================================================
MSG: cargo_ants_msgs/Polyline
# The polyline is walked in a clockwise direction, occupied space is
# to the right of each line segment between two consecutive points.
# In case the polyline is a polygon, the first point is repeated as
# the last point.

Point[] points

================================================================================
MSG: cargo_ants_msgs/Point
float32 px
float32 py
"""
  __slots__ = ['obstacles']
  _slot_types = ['cargo_ants_msgs/Obstacle[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       obstacles

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObstacleMap, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.obstacles is None:
        self.obstacles = []
    else:
      self.obstacles = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.obstacles)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacles:
        buff.write(_struct_I.pack(val1.type_tag))
        _v1 = val1.origin
        _x = _v1
        buff.write(_struct_3f.pack(_x.ox, _x.oy, _x.oth))
        length = len(val1.polylines)
        buff.write(_struct_I.pack(length))
        for val2 in val1.polylines:
          length = len(val2.points)
          buff.write(_struct_I.pack(length))
          for val3 in val2.points:
            _x = val3
            buff.write(_struct_2f.pack(_x.px, _x.py))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.obstacles is None:
        self.obstacles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacles = []
      for i in range(0, length):
        val1 = cargo_ants_msgs.msg.Obstacle()
        start = end
        end += 4
        (val1.type_tag,) = _struct_I.unpack(str[start:end])
        _v2 = val1.origin
        _x = _v2
        start = end
        end += 12
        (_x.ox, _x.oy, _x.oth,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.polylines = []
        for i in range(0, length):
          val2 = cargo_ants_msgs.msg.Polyline()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.points = []
          for i in range(0, length):
            val3 = cargo_ants_msgs.msg.Point()
            _x = val3
            start = end
            end += 8
            (_x.px, _x.py,) = _struct_2f.unpack(str[start:end])
            val2.points.append(val3)
          val1.polylines.append(val2)
        self.obstacles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.obstacles)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacles:
        buff.write(_struct_I.pack(val1.type_tag))
        _v3 = val1.origin
        _x = _v3
        buff.write(_struct_3f.pack(_x.ox, _x.oy, _x.oth))
        length = len(val1.polylines)
        buff.write(_struct_I.pack(length))
        for val2 in val1.polylines:
          length = len(val2.points)
          buff.write(_struct_I.pack(length))
          for val3 in val2.points:
            _x = val3
            buff.write(_struct_2f.pack(_x.px, _x.py))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.obstacles is None:
        self.obstacles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacles = []
      for i in range(0, length):
        val1 = cargo_ants_msgs.msg.Obstacle()
        start = end
        end += 4
        (val1.type_tag,) = _struct_I.unpack(str[start:end])
        _v4 = val1.origin
        _x = _v4
        start = end
        end += 12
        (_x.ox, _x.oy, _x.oth,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.polylines = []
        for i in range(0, length):
          val2 = cargo_ants_msgs.msg.Polyline()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.points = []
          for i in range(0, length):
            val3 = cargo_ants_msgs.msg.Point()
            _x = val3
            start = end
            end += 8
            (_x.px, _x.py,) = _struct_2f.unpack(str[start:end])
            val2.points.append(val3)
          val1.polylines.append(val2)
        self.obstacles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2f = struct.Struct("<2f")
_struct_3f = struct.Struct("<3f")
