# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cargo_ants_msgs/RadarObject209.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class RadarObject209(genpy.Message):
  _md5sum = "55b65dbd73b07d8169b3a3aef6dd3b37"
  _type = "cargo_ants_msgs/RadarObject209"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header            # timestamp in the header is the acquisition time of 
                         # the first ray in the scan.
                         #
                         # in frame frame_id, angles are measured around 
                         # the positive Z axis (counterclockwise, if Z is up)
                         # with zero angle being forward along the x axis

uint16 sensorId
uint16 obj_id			# unique object id
uint8 index				# index of object in the list
float32 longdisp		# longitudinal displacement	[m]
float32 latdisp			# lateral displacement [m]
float32 vrellong		# relative longitudinal velocity [m/s]
float32 vrellat			# relative lateral velocity	[m/s]
uint8 rollcount			# sequence index
float32 rcs				# radar cross-section [dBm^2]
float32 lifetime		# lifetime of track [s]
                        

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','sensorId','obj_id','index','longdisp','latdisp','vrellong','vrellat','rollcount','rcs','lifetime']
  _slot_types = ['std_msgs/Header','uint16','uint16','uint8','float32','float32','float32','float32','uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,sensorId,obj_id,index,longdisp,latdisp,vrellong,vrellat,rollcount,rcs,lifetime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarObject209, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sensorId is None:
        self.sensorId = 0
      if self.obj_id is None:
        self.obj_id = 0
      if self.index is None:
        self.index = 0
      if self.longdisp is None:
        self.longdisp = 0.
      if self.latdisp is None:
        self.latdisp = 0.
      if self.vrellong is None:
        self.vrellong = 0.
      if self.vrellat is None:
        self.vrellat = 0.
      if self.rollcount is None:
        self.rollcount = 0
      if self.rcs is None:
        self.rcs = 0.
      if self.lifetime is None:
        self.lifetime = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.sensorId = 0
      self.obj_id = 0
      self.index = 0
      self.longdisp = 0.
      self.latdisp = 0.
      self.vrellong = 0.
      self.vrellat = 0.
      self.rollcount = 0
      self.rcs = 0.
      self.lifetime = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2HB4fB2f.pack(_x.sensorId, _x.obj_id, _x.index, _x.longdisp, _x.latdisp, _x.vrellong, _x.vrellat, _x.rollcount, _x.rcs, _x.lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.sensorId, _x.obj_id, _x.index, _x.longdisp, _x.latdisp, _x.vrellong, _x.vrellat, _x.rollcount, _x.rcs, _x.lifetime,) = _struct_2HB4fB2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2HB4fB2f.pack(_x.sensorId, _x.obj_id, _x.index, _x.longdisp, _x.latdisp, _x.vrellong, _x.vrellat, _x.rollcount, _x.rcs, _x.lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.sensorId, _x.obj_id, _x.index, _x.longdisp, _x.latdisp, _x.vrellong, _x.vrellat, _x.rollcount, _x.rcs, _x.lifetime,) = _struct_2HB4fB2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_2HB4fB2f = struct.Struct("<2HB4fB2f")
