# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cargo_ants_msgs/Task.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cargo_ants_msgs.msg

class Task(genpy.Message):
  _md5sum = "4de459da6edc0969edecda788239a02b"
  _type = "cargo_ants_msgs/Task"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string vehicle
string container
Goal pickup
Goal placedown

================================================================================
MSG: cargo_ants_msgs/Goal
# A goal is specified as its (gx,gy) coordinate and heading gth (for
# "goal theta"). Additionally, dr is the radial tolerance, and dth the
# angular tolerance to be achieved. Specifying a negative number for
# either dr or dth disabled that particular tolerance. Thus, if you do
# no care about the heading with which you arrive at a goal, specify
# dth = -1 for example.  The goal message type is intended to be used
# as part of other messages such as Path.msg, thus we do not include
# the frame here as that should be the same for an entire array of
# goals.

float64 gx
float64 gy
float64 gth

# Radial accuracy of the goal. Specifying dr <= 0.0 means that you do
# not care about the goal position at all.
#
float64 dr

# Angular accuracy of the goal. Specifying dth <= 0.0 or >= M_PI means
# that orientation does not matter.
#
float64 dth


#later? bool go_forward
"""
  __slots__ = ['vehicle','container','pickup','placedown']
  _slot_types = ['string','string','cargo_ants_msgs/Goal','cargo_ants_msgs/Goal']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vehicle,container,pickup,placedown

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Task, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vehicle is None:
        self.vehicle = ''
      if self.container is None:
        self.container = ''
      if self.pickup is None:
        self.pickup = cargo_ants_msgs.msg.Goal()
      if self.placedown is None:
        self.placedown = cargo_ants_msgs.msg.Goal()
    else:
      self.vehicle = ''
      self.container = ''
      self.pickup = cargo_ants_msgs.msg.Goal()
      self.placedown = cargo_ants_msgs.msg.Goal()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.vehicle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.container
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10d.pack(_x.pickup.gx, _x.pickup.gy, _x.pickup.gth, _x.pickup.dr, _x.pickup.dth, _x.placedown.gx, _x.placedown.gy, _x.placedown.gth, _x.placedown.dr, _x.placedown.dth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pickup is None:
        self.pickup = cargo_ants_msgs.msg.Goal()
      if self.placedown is None:
        self.placedown = cargo_ants_msgs.msg.Goal()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle = str[start:end].decode('utf-8')
      else:
        self.vehicle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.container = str[start:end].decode('utf-8')
      else:
        self.container = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.pickup.gx, _x.pickup.gy, _x.pickup.gth, _x.pickup.dr, _x.pickup.dth, _x.placedown.gx, _x.placedown.gy, _x.placedown.gth, _x.placedown.dr, _x.placedown.dth,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.vehicle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.container
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10d.pack(_x.pickup.gx, _x.pickup.gy, _x.pickup.gth, _x.pickup.dr, _x.pickup.dth, _x.placedown.gx, _x.placedown.gy, _x.placedown.gth, _x.placedown.dr, _x.placedown.dth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pickup is None:
        self.pickup = cargo_ants_msgs.msg.Goal()
      if self.placedown is None:
        self.placedown = cargo_ants_msgs.msg.Goal()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle = str[start:end].decode('utf-8')
      else:
        self.vehicle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.container = str[start:end].decode('utf-8')
      else:
        self.container = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.pickup.gx, _x.pickup.gy, _x.pickup.gth, _x.pickup.dr, _x.pickup.dth, _x.placedown.gx, _x.placedown.gy, _x.placedown.gth, _x.placedown.dr, _x.placedown.dth,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_10d = struct.Struct("<10d")
